name: Deploy Frontend

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "frontend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci --prefer-offline --no-audit --progress=false

      - name: Build Nuxt frontend
        working-directory: ./frontend
        run: npm run build

      - name: Check build output
        run: ls -la frontend/.output

      - name: Copy build to Raspberry Pi
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.RPI_HOST }}
          username: ${{ secrets.RPI_USER }}
          key: ${{ secrets.RPI_SSH_KEY }}
          port: ${{ secrets.RPI_PORT }}
          script: |
            set -e
            TARGET_DIR=~/NohamDrive/frontend/.output
            echo "üßπ Nettoyage du dossier cible..."
            rm -rf $TARGET_DIR
            mkdir -p $TARGET_DIR

      - name: SCP frontend build to Raspberry Pi
        run: |
          scp -r -P ${{ secrets.RPI_PORT }} ./frontend/.output/* ${{ secrets.RPI_USER }}@${{ secrets.RPI_HOST }}:~/NohamDrive/frontend/.output/

      - name: Launch frontend Docker container
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.RPI_HOST }}
          username: ${{ secrets.RPI_USER }}
          key: ${{ secrets.RPI_SSH_KEY }}
          port: ${{ secrets.RPI_PORT }}
          script: |
            set -e
            APP_PATH=~/NohamDrive/frontend
            echo "üîÑ Arr√™t du conteneur frontend existant (si pr√©sent)..."
            docker compose -f $APP_PATH/docker-compose.frontend.yml down || true
            echo "üê≥ D√©marrage du conteneur frontend..."
            docker compose -f $APP_PATH/docker-compose.frontend.yml up -d --remove-orphans
            echo "üßπ Nettoyage des images Docker inutilis√©es..."
            docker image prune -f
            echo "‚úÖ D√©ploiement termin√© !"
